##############################################
# Authors Section
# Append your information here:
##############################################
authors:
  matthieulapeyre:
    display_name: Matthieu Lapeyre
    gravatar: ef7c64d1a92babba8d87df3436ecef68
    email: matthieulapeyre@gmail.com
    website:
    social:
        github: matthieu-lapeyre
        linkedin: in/matthieulapeyre


##############################################
# Wiki configuration
# DO NOT TOUCH !
##############################################

name: Poppy project wiki
baseurl: /wiki
# permalink: pretty
permalink: /:categories/:title
markdown: rdiscount
ignore:
    - /_includes
    - /_layouts
    - /_site
    - .gitignore
    - Gemfile
    - index.md
    - LICENCE.md
    - links.jsonp
    - README.md
    - style.css
prose:
  siteurl: 'http://poppy-project.github.io/wiki/'
  relativeLinks: 'http://poppy-project.github.io/wiki/links.jsonp'
  media: 'media'
  metadata:
    _posts/updates:
      - name: "layout"
        field:
          element: "hidden"
          value: "update_note"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "category"
        field:
          element: "select"
          placeholder: "Choose category"
          options:
            - name: "News"
              value: "news"
            - name: "Issue"
              value: "issue"
            - name: "Bug"
              value: "bug"
            - name: "Fix"
              value: "fix"
    _posts/documentation:
      - name: "layout"
        field:
          element: "hidden"
          value: "documentation"
      - name: "category"
        field:
          element: "hidden"
          value: "documentation"
      - name: "title"
        field:
          element: "text"
          label: "Document title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "sidemenu"
        field:
          element: "textarea"
          label: "Title"
          value: ""
    _posts/tutorial:
      - name: "layout"
        field:
          element: "hidden"
          value: "documentation"
      - name: "category"
        field:
          element: "hidden"
          value: "tutorial"
      - name: "title"
        field:
          element: "text"
          label: "Document title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "sidemenu"
        field:
          element: "textarea"
          label: "Title"
          value: ""
